### ISSUE TITLE
node-sass errors during grunt watch sass compiles

### ISSUE THREAD

**Issue by jerseycheese** [JoshEllinger/JointsWP-child#2]
I've tried reinstalling node-sass as suggested in here, but get the same error(s) afterwards.  Any ideas?  Thanks in advance.

```
My-MacBook-Pro:JointsWP-child jerseycheese$ grunt watch
Loading "sass.js" tasks...ERROR
>> Error: `/Applications/MAMP/htdocs/site/wp-content/themes/JointsWP-child/node_modules/grunt-sass/node_modules/node-sass/bin/darwin-x64-v8-3.11/binding.node` is missing. Try reinstalling `node-sass`?

Running "watch" task
Waiting...OK
>> File "sass/main.scss" changed.

Loading "sass.js" tasks...ERROR
>> Error: `/Applications/MAMP/htdocs/site/wp-content/themes/JointsWP-child/node_modules/grunt-sass/node_modules/node-sass/bin/darwin-x64-v8-3.11/binding.node` is missing. Try reinstalling `node-sass`?
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.
Completed in 0.753s at Fri Feb 07 2014 11:36:42 GMT-0500 (EST) - Waiting...
```

**Comment by JoshEllinger** [comment]
I just updated the package.json, which might help

Try running this first:

```
npm install -g grunt-cli
```

Then inside the JointsWP-child directory run

```
npm install 
```

This should install all the dependencies locally

**Comment by jerseycheese** [comment]
Hmm, ok, so

```
npm install -g grunt-cli
```

worked out OK (had to sudo):

```
My-MacBook-Pro:JointsWP-child jerseycheese$ sudo npm install -g grunt-cli
Password:
npm http GET https://registry.npmjs.org/grunt-cli
npm http 304 https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/resolve
npm http 200 https://registry.npmjs.org/findup-sync
npm http 200 https://registry.npmjs.org/resolve
npm http 200 https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/glob
npm http 200 https://registry.npmjs.org/abbrev
npm http 200 https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/graceful-fs
npm http 200 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 200 https://registry.npmjs.org/sigmund
npm http 200 https://registry.npmjs.org/lru-cache
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
grunt-cli@0.1.13 /usr/local/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.4)
└── findup-sync@0.1.2 (lodash@1.0.1, glob@3.1.21)

```

But then ...

```
My-MacBook-Pro:JointsWP-child jerseycheese$ sudo npm install 
npm WARN prefer global bower@1.2.8 should be installed with -g
npm WARN prefer global grunt-cli@0.1.12 should be installed with -g

> node-sass@0.8.1 install /Applications/MAMP/htdocs/mysite/wp-content/themes/JointsWP-child/node_modules/node-sass
> node build.js

`darwin-x64-v8-3.11` exists; testing

  ․․․․․․․․․․․․․․․․․

  16 passing (19ms)
  1 failing

  1) compile file with include paths should compile with render:
     Error: done() invoked with non-Error: /Applications/MAMP/htdocs/mysite/wp-content/themes/JointsWP-child/node_modules/node-sass/test/include_path.scss:1: error: file to import not found or unreadable: "vars"

      at Runnable.run.duration (/Applications/MAMP/htdocs/mysite/wp-content/themes/JointsWP-child/node_modules/node-sass/node_modules/mocha/lib/runnable.js:196:38)
      at sass.render.error (/Applications/MAMP/htdocs/mysite/wp-content/themes/JointsWP-child/node_modules/node-sass/test/test.js:130:9)



Problem with the binary; manual build incoming
Please consider contributing the release binary to https://github.com/andrew/node-sass-binaries for npm distribution.
  CXX(target) Release/obj.target/binding/binding.o
  CXX(target) Release/obj.target/binding/sass_context_wrapper.o
  CXX(target) Release/obj.target/binding/libsass/ast.o
  CXX(target) Release/obj.target/binding/libsass/base64vlq.o
  CXX(target) Release/obj.target/binding/libsass/bind.o
  CXX(target) Release/obj.target/binding/libsass/constants.o
  CXX(target) Release/obj.target/binding/libsass/context.o
  CXX(target) Release/obj.target/binding/libsass/contextualize.o
  CXX(target) Release/obj.target/binding/libsass/copy_c_str.o
  CXX(target) Release/obj.target/binding/libsass/error_handling.o
  CXX(target) Release/obj.target/binding/libsass/eval.o
  CXX(target) Release/obj.target/binding/libsass/expand.o
  CXX(target) Release/obj.target/binding/libsass/extend.o
  CXX(target) Release/obj.target/binding/libsass/file.o
  CXX(target) Release/obj.target/binding/libsass/functions.o
  CXX(target) Release/obj.target/binding/libsass/inspect.o
  CXX(target) Release/obj.target/binding/libsass/output_compressed.o
  CXX(target) Release/obj.target/binding/libsass/output_nested.o
  CXX(target) Release/obj.target/binding/libsass/parser.o
  CXX(target) Release/obj.target/binding/libsass/prelexer.o
  CXX(target) Release/obj.target/binding/libsass/sass.o
  CXX(target) Release/obj.target/binding/libsass/sass_interface.o
  CXX(target) Release/obj.target/binding/libsass/source_map.o
  CXX(target) Release/obj.target/binding/libsass/to_c.o
  CXX(target) Release/obj.target/binding/libsass/to_string.o
  CXX(target) Release/obj.target/binding/libsass/units.o
  SOLINK_MODULE(target) Release/binding.node
  SOLINK_MODULE(target) Release/binding.node: Finished
Installed in `/Applications/MAMP/htdocs/mysite/wp-content/themes/JointsWP-child/node_modules/node-sass/bin/darwin-x64-v8-3.11/binding.node`
```

Then I tried a "grunt watch" just to see what happens...

```
Jacks-MacBook-Pro:JointsWP-child advojack$ grunt watch
Loading "sass.js" tasks...ERROR
>> Error: `/Applications/MAMP/htdocs/mysite/wp-content/themes/JointsWP-child/node_modules/grunt-sass/node_modules/node-sass/bin/darwin-x64-v8-3.11/binding.node` is missing. Try reinstalling `node-sass`?

Running "watch" task
Waiting...OK
>> File "sass/main.scss" changed.

Loading "sass.js" tasks...ERROR
>> Error: `/Applications/MAMP/htdocs/mysite/wp-content/themes/JointsWP-child/node_modules/grunt-sass/node_modules/node-sass/bin/darwin-x64-v8-3.11/binding.node` is missing. Try reinstalling `node-sass`?
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.
Completed in 0.799s at Fri Feb 14 2014 11:55:30 GMT-0500 (EST) - Waiting...
```

Which is exactly what happened originally on a "grunt watch".

**Comment by JoshEllinger** [comment]
First try this:

```
npm install --save-dev
```

if that doesn't work...
This looks like a node-sass issue, related to libsass/sassc/node-sass (the non ruby implementation).

Node-sass is literally trying to compile libsass/sassc on your computer and something is failing, which is really more an issue with node-sass, if you want to continue trying to get node sass to work, this issue queue may be able to better help...
https://github.com/andrew/node-sass/issues

While not as sexy and fast, if you have (ruby) sass installed, you could try using grunt-contrib-sass.
Just find this in the gruntfile.js, and follow the instructions.

```
    // Comment here and uncomment the other task to use ruby sass
    grunt.loadNpmTasks('grunt-sass'); // sassc
    //grunt.loadNpmTasks('grunt-contrib-sass'); // ruby sass
```

**Comment by KimPeeters** [comment]
Had the same error, but after updating node to a newer version, the problem was solved.

**Comment by besabellacyrus** [comment]
adding sudo both 
sudo npm install -g grunt-cli
sudo npm install

did the trick, Thanks!
